services:
  redis:
    image: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - ./src/data/db/dumps:/app-db-dumps

  redis-test:
    image: redis
    command: ["redis-server"]
    ports:
      - "6380:6379"
    volumes:
      - ./src/data/db/dumps:/app-db-dumps
